### ISSUE TITLE
Dear author, how to get the label 0, 0.5, 1 and what do these scores mean?

### ISSUE THREAD

**Issue by fywang12** [ljcleo/Debatrix#2]

**Comment by ljcleo** [comment]
In DebateArt, votes can have ties sometimes, so we assign "Pro Wins", "Tie" and "Con Wins" to labels 0, 0.5 and 1 respectively.

Could you clarify what "these scores" you mentioned refer to? We have involved multiple metrics in the paper.

**Comment by GorgeousWang** [comment]
Thanks.Are the labeling results of the dataset based on a majority vote among the results of multiple voters?

**Comment by fywang12** [comment]
Thanks for your reply.
I mean, for each debate, how do you get the final annotation labels based on the votes of multiple annotators?

**Comment by ljcleo** [comment]
The final labels per dimension and the general verdicts are calculated based on DebateArt (the website)'s rules:

- Each voter chooses a winning side that earns one point (or announce a tie and gives both sides one point) for each dimension.
- Within each dimension, the side with higher points wins in that dimension; if both sides get the same points then it's a tie.
- The final winner is decided by the weighed sum of points from each dimension (the side with higher points wins/tie if points are equal).

You can take [this debate](https://www.debateart.com/debates/17) as an example, which is the first debate in the DebateArt collection of PanelBench.

Specifically, we merged the latter two dimensions (legibility and conduct) into one language dimension. This was done per vote: if the voter votes one side in both old dimensions or votes one side in one dimension and announces a tie in another, then that side gets the vote in the new dimension, otherwise it becomes a tie. We calculated its dimensional label according to the same rules. The new dimension's weight is the sum of the two old dimensions' weights.

**Comment by fywang12** [comment]
> The final labels per dimension and the general verdicts are calculated based on DebateArt (the website)'s rules:
> 
> 
> 
> - Each voter chooses a winning side that earns one point (or announce a tie and gives both sides one point) for each dimension.
> 
> - Within each dimension, the side with higher points wins in that dimension; if both sides get the same points then it's a tie.
> 
> - The final winner is decided by the weighed sum of points from each dimension (the side with higher points wins/tie if points are equal).
> 
> 
> 
> You can take [this debate](https://www.debateart.com/debates/17) as an example, which is the first debate in the DebateArt collection of PanelBench.
> 
> 
> 
> Specifically, we merged the latter two dimensions (legibility and conduct) into one language dimension. This was done per vote: if the voter votes one side in both old dimensions or votes one side in one dimension and announces a tie in another, then that side gets the vote in the new dimension, otherwise it becomes a tie. We calculated its dimensional label according to the same rules. The new dimension's weight is the sum of the two old dimensions' weights.

thanks
